force-app/main/default/objects/Account/fields/Exclude_From_Monitoring_Set__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Monitoring_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude From Monitoring Set</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsInMonitoringSet__c.field-meta.xml
<CustomField>
    <fullName>IsInMonitoringSet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInMonitoringSet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Period__c.field-meta.xml
<CustomField>
    <fullName>Latest_Period__c</fullName>
    <label>Latest Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Year_Result__c.field-meta.xml
<CustomField>
    <fullName>Latest_Year_Result__c</fullName>
    <label>Latest Year Result</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Period_Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Period_Duration_In_Months__c</fullName>
    <label>Period Duration In Months</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/Valitive_Event__c.object-meta.xml
<CustomObject>
    <label>Valitive Event</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valitive Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Kind__c.field-meta.xml
<CustomField>
    <fullName>Address_Kind__c</fullName>
    <label>Address Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OFFICIAL</fullName>
            </value>
            <value>
                <fullName>FORWARD_MAIL</fullName>
            </value>
            <value>
                <fullName>FOREIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Months__c</fullName>
    <label>Duration In Months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/New_KPI_Result_Value__c.field-meta.xml
<CustomField>
    <fullName>New_KPI_Result_Value__c</fullName>
    <label>New KPI Result Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Org_Status__c.field-meta.xml
<CustomField>
    <fullName>Org_Status__c</fullName>
    <label>Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Postbox__c.field-meta.xml
<CustomField>
    <fullName>Postbox__c</fullName>
    <label>Postbox</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountValitiveEventMapping.cls
public class AccountValitiveEventMapping {

    static ValitiveUtils valitiveUtils = new ValitiveUtils();

    public static Account mapOrgStatusChangedEventToAccount(Account acc, Valitive_Event__c event) {
 
        acc.Status__c = event.Org_Status__c;
        return acc;
    }

    public static Account mapOrgNameChangedEventToAccount(Account acc, Valitive_Event__c event) {
        
        acc.Name = event.Org_Name__c;
        return acc;
    }

    public static Account mapOrgAddrChangedEventToAccount(Account acc, Valitive_Event__c event) {
        if(event.Address_Kind__c == 'MAIL'){
            acc.BillingCity = event.City__c.toUpperCase();
            acc.BillingState = event.County__c;
            acc.BillingPostalCode = valitiveUtils.formatZipCode(event.Zip__c);
            acc.BillingCountry = event.Country_Code__c;
            if(event.Postbox__c != null){
                acc.BillingStreet = event.Postbox__c;
            } else {
                acc.BillingStreet = valitiveUtils.constructAdressSteetString(event);
            }
        }

        return acc;
    }

    public static Account mapOrgAddrCorrectedEventToAccount(Account acc, Valitive_Event__c event) {
        if(event.Address_Kind__c == 'MAIL'){
            acc.BillingCity = event.City__c.toUpperCase();
            acc.BillingState = event.County__c;
            acc.BillingPostalCode = valitiveUtils.formatZipCode(event.Zip__c);
            acc.BillingCountry = event.Country_Code__c;
            if(event.Postbox__c != null){
                acc.BillingStreet = event.Postbox__c;
            } else {
                acc.BillingStreet = valitiveUtils.constructAdressSteetString(event);
            }
        }

        return acc;
    }

    public static Account mapOrgKPIResultChangedEventToAccount(Account acc, Valitive_Event__c event) {
        
        acc.Latest_Period__c = event.Period__c;
        acc.Period_Duration_In_Months__c = event.Duration_In_Months__c != null ? Integer.valueOf(event.Duration_In_Months__c) : null;
        acc.Latest_Year_Result__c = event.New_KPI_Result_Value__c;
        return acc;
    }

    public static Account mapOrgArchivedEventToAccount(Account acc, Valitive_Event__c event) {
        
        acc.IsInMonitoringSet__c = false;
        acc.Exclude_From_Monitoring_Set__c = true;
        return acc;
    }
}