force-app/main/default/objects/Account/fields/Valitive_Import_Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Valitive_Import_Process_Id__c</fullName>
    <label>Valitive Import Process Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Valitive_Import_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Valitive_Import_Process_Status__c</fullName>
    <label>Valitive Import Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Initial Sync</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ValitiveImportProcessBatch.cls
public class ValitiveImportProcessBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {


    @TestVisible
    private final ValitiveService valitiveService = new ValitiveService();


    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT 
                Id,
                Valitive_Import_Process_Id__c,
                Valitive_Import_Process_Status__c
            FROM Account 
            WHERE 
                Valitive_Import_Process_Status__c = 'Pending'
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Account> accounts) {

        List<Database.SaveResult> results = new List<Database.SaveResult>();
        List<Account> accountsToUpdate = new List<Account>();

        for (Account account : accounts) {
            HttpResponse response = valitiveService.getImportProcessStatus(account.Valitive_Import_Process_Id__c);
            if (response.getStatusCode() == 200) {
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                String status = (String) responseMap.get('status');
                switch on status {
                    when 'COMPLETED' {
                        account.Valitive_Import_Process_Status__c = 'Awaiting Initial Sync';
                    }
                    when 'STALLED' {
                        account.Valitive_Import_Process_Status__c = 'Failed';
                    }
                }
            } 
            accountsToUpdate.add(account);
        }

        if (!accountsToUpdate.isEmpty()) {
            results = Database.update(accountsToUpdate, false);
        }

    }

    public void finish(Database.BatchableContext BC) {
    }

}