force-app/main/default/objects/Contact/fields/Has_Trustee__c.field-meta.xml
<CustomField>
    <fullName>Has_Trustee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Trustee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Has_Trustee_Since__c.field-meta.xml
<CustomField>
    <fullName>Has_Trustee_Since__c</fullName>
    <label>Has Trustee Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/Valitive_Event__c.object-meta.xml
<CustomObject>
    <label>Valitive Event</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valitive Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Kind__c.field-meta.xml
<CustomField>
    <fullName>Address_Kind__c</fullName>
    <label>Address Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OFFICIAL</fullName>
            </value>
            <value>
                <fullName>FORWARD_MAIL</fullName>
            </value>
            <value>
                <fullName>FOREIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RAW</fullName>
            </value>
            <value>
                <fullName>SE_NORMALIZED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Area_Code__c</fullName>
    <label>Area Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On__c</fullName>
    <label>Deceased On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On_Month__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On_Month__c</fullName>
    <label>Deceased On Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On_Year__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On_Year__c</fullName>
    <label>Deceased On Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Detected_At__c.field-meta.xml
<CustomField>
    <fullName>Detected_At__c</fullName>
    <label>Detected At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Given_Name__c</fullName>
    <label>Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Guarded_Since__c.field-meta.xml
<CustomField>
    <fullName>Guarded_Since__c</fullName>
    <label>Guarded Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Guardianship_Type__c.field-meta.xml
<CustomField>
    <fullName>Guardianship_Type__c</fullName>
    <label>Guardianship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GUARDIANSHIP</fullName>
            </value>
            <value>
                <fullName>LIMITED_GUARDIANSHIP</fullName>
            </value>
            <value>
                <fullName>EXTENDED_GUARDIANSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <label>Municipality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Person_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_Id__c</fullName>
    <label>Person Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Person_Legal_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_Legal_Id__c</fullName>
    <label>Person Legal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Phone_Kind__c.field-meta.xml
<CustomField>
    <fullName>Phone_Kind__c</fullName>
    <label>Phone Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOBILE</fullName>
            </value>
            <value>
                <fullName>LANDLINE</fullName>
            </value>
            <value>
                <fullName>SWITCHBOARD</fullName>
            </value>
            <value>
                <fullName>OFFICIAL</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Property_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Property_Identifier__c</fullName>
    <label>Property Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Registered_Since__c.field-meta.xml
<CustomField>
    <fullName>Registered_Since__c</fullName>
    <label>Registered Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Since__c.field-meta.xml
<CustomField>
    <fullName>Since__c</fullName>
    <label>Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Contact Sync</fullName>
                <default>true</default>
                <label>Awaiting Contact Sync</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Awaiting Manual Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Number__c</fullName>
    <label>Telephone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SE_PERSON_ADDR_CHANGED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_ADDR_CORRECTED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_DECEASED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_NAME_CHANGED</fullName>
            </value>
            <value>
                <fullName>PHONE_BOUND</fullName>
            </value>
            <value>
                <fullName>PHONE_UNBOUND</fullName>
            </value>
            <value>
                <fullName>PERSON_PROTECTION_ACTIVATED</fullName>
            </value>
            <value>
                <fullName>PERSON_PROTECTION_DEACTIVATED</fullName>
            </value>
            <value>
                <fullName>PERSON_LEGAL_ID_CHANGED</fullName>
            </value>
            <value>
                <fullName>PERSON_GENDER_CHANGED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Valid_Since__c.field-meta.xml
<CustomField>
    <fullName>Valid_Since__c</fullName>
    <label>Valid Since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Test_ContactValitiveEventSyncBatch.cls
@IsTest
private class Test_ContactValitiveEventSyncBatch {
    
    private static String newNameContactLegalId = '19910101-0000';
    private static String deceasedContactLegalId = '19910101-0001';
    private static String phoneBoundContactLegalId = '19910101-0002';
    private static String phoneUnboundContactLegalId = '19910101-0003';
    private static String protectionActivatedContactLegalId = '19910101-0004';
    private static String protectionDeactivatedContactLegalId = '19910101-0005';
    private static String guardActivatedContactLegalId = '19910101-0006';
    private static String guardDeactivatedContactLegalId = '19910101-0007';
    private static String addrChangedContactLegalId = '19910101-0008';
    private static String addrCorrectedContactLegalId = '19910101-0009';


    @TestSetup
    static void makeData(){

        Contact newNameContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = newNameContactLegalId
        );

        Contact newDeceasedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = deceasedContactLegalId
        );

        Contact newPhoneBoundContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = phoneBoundContactLegalId
        );

        Contact newPhoneUnboundContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = phoneUnboundContactLegalId
        );

        Contact newProtectionActivatedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = protectionActivatedContactLegalId,
            Protected_Identity__c = false
        );

        Contact newProtectionDeactivatedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = protectionDeactivatedContactLegalId,
            Protected_Identity__c = true
        );

        Contact newGuardActivatedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = guardActivatedContactLegalId,
            Has_Trustee__c = false,
            Has_Trustee_Since__c = null
        );

        Contact newGuardDeactivatedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = guardDeactivatedContactLegalId,
            Has_Trustee__c = true,
            Has_Trustee_Since__c = Date.today()
        );

        Contact newAddrChangedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = addrChangedContactLegalId
        );

        Contact newAddrCorrectedContact = new Contact(
            FirstName = 'Test',
            LastName = 'Testsson',
            Personal_Identity_Number__c = addrCorrectedContactLegalId
        );
        
        List<Contact> contacts = new List<Contact>{
            newNameContact, 
            newDeceasedContact, 
            newPhoneBoundContact, 
            newPhoneUnboundContact,
            newProtectionActivatedContact, 
            newProtectionDeactivatedContact,
            newGuardActivatedContact, 
            newGuardDeactivatedContact,
            newAddrChangedContact,
            newAddrCorrectedContact
        };
        insert contacts;

        Valitive_Event__c personGuardAddedEvent = new Valitive_Event__c(
            Event_Id__c = '1',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newGuardActivatedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_GUARD_ADDED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Guardianship_Type__c = 'GUARDIANSHIP',
            Guarded_Since__c = Date.today(),
            Contact__c = newGuardActivatedContact.Id
        );

        Valitive_Event__c personGuardRemovedEvent = new Valitive_Event__c(
            Event_Id__c = '2',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newGuardDeactivatedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_GUARD_REMOVED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Contact__c = newGuardDeactivatedContact.Id
        );


        Valitive_Event__c phoneBoundEvent = new Valitive_Event__c(
            Event_Id__c = '9',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newPhoneBoundContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'PHONE_BOUND',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Phone_Kind__c = 'MOBILE',
            Telephone_Number__c = '46760000000',
            Country_Code__c = '46',
            Area_Code__c = '08',
            Registered_Since__c = Date.today(),
            Provider__c = 'TELIA',
            Contact__c = newPhoneBoundContact.Id
        );

        Valitive_Event__c phoneUnboundEvent = new Valitive_Event__c(
            Event_Id__c = '3',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newPhoneUnboundContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'PHONE_UNBOUND',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Phone_Kind__c = 'MOBILE',
            Telephone_Number__c = '46760000000',
            Country_Code__c = '46',
            Area_Code__c = '08',
            Provider__c = 'TELIA',
            Contact__c = newPhoneUnboundContact.Id
        );

        Valitive_Event__c personProtectionActivatedEvent = new Valitive_Event__c(
            Event_Id__c = '4',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newProtectionActivatedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'PERSON_PROTECTION_ACTIVATED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Since__c = Date.today(),
            Contact__c = newProtectionActivatedContact.Id
        );

        Valitive_Event__c personProtectionDeactivatedEvent = new Valitive_Event__c(
            Event_Id__c = '5',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newProtectionDeactivatedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'PERSON_PROTECTION_DEACTIVATED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Since__c = Date.today(),
            Contact__c = newProtectionDeactivatedContact.Id
        );

        Valitive_Event__c personDeceasedEvent = new Valitive_Event__c(
            Event_Id__c = '123',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newDeceasedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_PERSON_DECEASED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Deceased_On__c = Date.today(),
            Deceased_On_Month__c = '2024-02',
            Deceased_On_Year__c = 2024,
            Contact__c = newDeceasedContact.Id
        );

        Valitive_Event__c personAddrChangedEvent = new Valitive_Event__c(
            Event_Id__c = '6',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newAddrChangedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_PERSON_ADDR_CHANGED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Address_Type__c = 'SE_NORMALIZED',
            Address_Kind__c = 'OFFICIAL',
            Country__c = 'Sweden',
            County__c = 'Stockholms län',
            City__c = 'STOCKHOLM',
            Zip__c = '12345',
            Street__c = 'Testgatan Changed',
            Property_Identifier__c = '1',
            Flat__c = '1',
            Municipality__c = 'Stockholm',
            Contact__c = newAddrChangedContact.Id
        );

        Valitive_Event__c personAddrCorrectedEvent = new Valitive_Event__c(
            Event_Id__c = '7',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newAddrCorrectedContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_PERSON_ADDR_CORRECTED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Address_Type__c = 'SE_NORMALIZED',
            Address_Kind__c = 'OFFICIAL',
            Country__c = 'Sweden',
            County__c = 'Stockholms län',
            City__c = 'STOCKHOLM',
            Zip__c = '12345',
            Street__c = 'Testgatan Corrected',
            Property_Identifier__c = '1',
            Flat__c = '1',
            Municipality__c = 'Stockholm',
            Contact__c = newAddrCorrectedContact.Id
        );

        Valitive_Event__c personNameChangeEvent = new Valitive_Event__c(
            Event_Id__c = '8',
            Detected_At__c = Datetime.now(),
            Person_Legal_Id__c = newNameContact.Personal_Identity_Number__c.replace('-', ''),
            Type__c = 'SE_PERSON_NAME_CHANGED',
            Person_Id__c = '1',
            Timestamp__c = Datetime.now(),
            Given_Name__c = 'New Test',
            FirstName__c = 'New Test Test',
            LastName__c = 'New Testsson',
            Valid_Since__c = Date.today(),
            Contact__c = newNameContact.Id
        );

        List<Valitive_Event__c> events = new List<Valitive_Event__c>{
            personGuardAddedEvent,
            personGuardRemovedEvent,
            phoneBoundEvent,
            phoneUnboundEvent,
            personProtectionActivatedEvent,
            personProtectionDeactivatedEvent,
            personDeceasedEvent,
            personAddrChangedEvent,
            personAddrCorrectedEvent,
            personNameChangeEvent
        };

        insert events;
    }

    @IsTest
    static void should_update_contact_name(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT FirstName, LastName FROM Contact WHERE Personal_Identity_Number__c = :newNameContactLegalId];
        System.assertEquals('New Test', contact.FirstName);
        System.assertEquals('New Testsson', contact.LastName);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_PERSON_NAME_CHANGED'];
        System.assertEquals('Completed', event.Sync_Status__c);
    }

    @IsTest
    static void should_update_contact_deceased(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT npsp__Deceased__c, Deceased_Date__c FROM Contact WHERE Personal_Identity_Number__c = :deceasedContactLegalId];
        System.assertEquals(true, contact.npsp__Deceased__c);
        System.assertEquals(Date.today(), contact.Deceased_Date__c);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_PERSON_DECEASED'];
        System.assertEquals('Completed', event.Sync_Status__c);
    }

    @IsTest
    static void should_update_contact_phone_bound(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT Phone, MobilePhone FROM Contact WHERE Personal_Identity_Number__c = :phoneBoundContactLegalId];
        System.assertEquals('0760000000', contact.MobilePhone);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'PHONE_BOUND'];
        System.assertEquals('Completed', event.Sync_Status__c);

    }

    @IsTest
    static void should_update_person_addr_changed(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT MailingStreet, MailingCity, MailingCountry, MailingPostalCode FROM Contact WHERE Personal_Identity_Number__c = :addrChangedContactLegalId];
        System.assertEquals('Testgatan Changed 1 lgh 1', contact.MailingStreet);
        System.assertEquals('STOCKHOLM', contact.MailingCity);
        // System.assertEquals('Sweden', contact.MailingCountry);
        System.assertEquals('123 45', contact.MailingPostalCode);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_PERSON_ADDR_CHANGED'];
        System.assertEquals('Completed', event.Sync_Status__c);
    }

    @IsTest
    static void should_update_person_addr_corrected(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT MailingStreet, MailingCity, MailingCountry, MailingPostalCode FROM Contact WHERE Personal_Identity_Number__c = :addrCorrectedContactLegalId];
        System.assertEquals('Testgatan Corrected 1 lgh 1', contact.MailingStreet);
        System.assertEquals('STOCKHOLM', contact.MailingCity);
        // System.assertEquals('Sweden', contact.MailingCountry);
        System.assertEquals('123 45', contact.MailingPostalCode);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_PERSON_ADDR_CORRECTED'];
        System.assertEquals('Completed', event.Sync_Status__c);
    }

    @IsTest
    static void should_update_person_protection_activated(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT Protected_Identity__c FROM Contact WHERE Personal_Identity_Number__c = :protectionActivatedContactLegalId];
        System.assertEquals(true, contact.Protected_Identity__c);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'PERSON_PROTECTION_ACTIVATED'];
        System.assertEquals('Completed', event.Sync_Status__c);

    }

    @IsTest
    static void should_update_person_protection_deactivated(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT Protected_Identity__c FROM Contact WHERE Personal_Identity_Number__c = :protectionDeactivatedContactLegalId];
        System.assertEquals(false, contact.Protected_Identity__c);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'PERSON_PROTECTION_DEACTIVATED'];
        System.assertEquals('Completed', event.Sync_Status__c);

    }

    @IsTest
    static void should_update_person_guard_added(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT Has_Trustee__c, Has_Trustee_Since__c FROM Contact WHERE Personal_Identity_Number__c = :guardActivatedContactLegalId];
        System.assertEquals(true, contact.Has_Trustee__c);
        System.assertEquals(Date.today(), contact.Has_Trustee_Since__c);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_GUARD_ADDED'];
        System.assertEquals('Completed', event.Sync_Status__c);

    }

    @IsTest
    static void should_update_person_guard_removed(){
        Test.startTest();
        Database.executeBatch(new ContactValitiveEventSyncBatch());
        Test.stopTest();
        Contact contact = [SELECT Has_Trustee__c, Has_Trustee_Since__c FROM Contact WHERE Personal_Identity_Number__c = :guardDeactivatedContactLegalId];
        System.assertEquals(false, contact.Has_Trustee__c);
        System.assertEquals(null, contact.Has_Trustee_Since__c);
        Valitive_Event__c event = [SELECT Sync_Status__c FROM Valitive_Event__c WHERE Type__c = 'SE_GUARD_REMOVED'];
        System.assertEquals('Completed', event.Sync_Status__c);

    }


}