force-app/main/default/objects/Valitive_Event__c/Valitive_Event__c.object-meta.xml
<CustomObject>
    <label>Valitive Event</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valitive Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Valitive_Event__c/fields/Additional_Street_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Street_Info__c</fullName>
    <label>Additional Street Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Kind__c.field-meta.xml
<CustomField>
    <fullName>Address_Kind__c</fullName>
    <label>Address Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OFFICIAL</fullName>
            </value>
            <value>
                <fullName>FORWARD_MAIL</fullName>
            </value>
            <value>
                <fullName>FOREIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Lines__c.field-meta.xml
<CustomField>
    <fullName>Address_Lines__c</fullName>
    <label>Address Lines</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RAW</fullName>
            </value>
            <value>
                <fullName>SE_NORMALIZED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Area_Code__c</fullName>
    <label>Area Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Care_Of__c.field-meta.xml
<CustomField>
    <fullName>Care_Of__c</fullName>
    <label>Care Of</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On__c</fullName>
    <label>Deceased On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On_Month__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On_Month__c</fullName>
    <label>Deceased On Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Deceased_On_Year__c.field-meta.xml
<CustomField>
    <fullName>Deceased_On_Year__c</fullName>
    <label>Deceased On Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
            </value>
            <value>
                <fullName>FEMALE</fullName>
            </value>
            <value>
                <fullName>BIGENDER</fullName>
            </value>
            <value>
                <fullName>UNDEFINED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Given_Name__c</fullName>
    <label>Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Guarded_Since__c.field-meta.xml
<CustomField>
    <fullName>Guarded_Since__c</fullName>
    <label>Guarded Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Guardianship_Type__c.field-meta.xml
<CustomField>
    <fullName>Guardianship_Type__c</fullName>
    <label>Guardianship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GUARDIANSHIP</fullName>
            </value>
            <value>
                <fullName>LIMITED_GUARDIANSHIP</fullName>
            </value>
            <value>
                <fullName>EXTENDED_GUARDIANSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Misc__c.field-meta.xml
<CustomField>
    <fullName>Misc__c</fullName>
    <label>Misc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <label>Municipality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Number_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Number_Suffix__c</fullName>
    <label>Number Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Additional_Street_Info__c.field-meta.xml
<CustomField>
    <fullName>Old_Additional_Street_Info__c</fullName>
    <label>Old Additional Street Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Address_Kind__c.field-meta.xml
<CustomField>
    <fullName>Old_Address_Kind__c</fullName>
    <label>Old Address Kind</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Old_Address_Type__c</fullName>
    <label>Old Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RAW</fullName>
            </value>
            <value>
                <fullName>SE_NORMALIZED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Care_Of__c.field-meta.xml
<CustomField>
    <fullName>Old_Care_Of__c</fullName>
    <label>Old Care Of</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_City__c.field-meta.xml
<CustomField>
    <fullName>Old_City__c</fullName>
    <label>Old City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Country__c.field-meta.xml
<CustomField>
    <fullName>Old_Country__c</fullName>
    <label>Old Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_County__c.field-meta.xml
<CustomField>
    <fullName>Old_County__c</fullName>
    <label>Old County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Old_FirstName__c</fullName>
    <label>Old FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Flat__c.field-meta.xml
<CustomField>
    <fullName>Old_Flat__c</fullName>
    <label>Old Flat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Gender__c.field-meta.xml
<CustomField>
    <fullName>Old_Gender__c</fullName>
    <label>Old Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
            </value>
            <value>
                <fullName>FEMALE</fullName>
            </value>
            <value>
                <fullName>BIGENDER</fullName>
            </value>
            <value>
                <fullName>UNDEFINED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Old_Given_Name__c</fullName>
    <label>Old Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_LastName__c.field-meta.xml
<CustomField>
    <fullName>Old_LastName__c</fullName>
    <label>Old LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Legal_Id__c.field-meta.xml
<CustomField>
    <fullName>Old_Legal_Id__c</fullName>
    <label>Old Legal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_MiddleName__c.field-meta.xml
<CustomField>
    <fullName>Old_MiddleName__c</fullName>
    <label>Old MiddleName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Municipality__c.field-meta.xml
<CustomField>
    <fullName>Old_Municipality__c</fullName>
    <label>Old Municipality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Number_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Old_Number_Suffix__c</fullName>
    <label>Old Number Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Postbox__c.field-meta.xml
<CustomField>
    <fullName>Old_Postbox__c</fullName>
    <label>Old Postbox</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Property_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Old_Property_Identifier__c</fullName>
    <label>Old Property Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Street__c.field-meta.xml
<CustomField>
    <fullName>Old_Street__c</fullName>
    <label>Old Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Old_Zip__c.field-meta.xml
<CustomField>
    <fullName>Old_Zip__c</fullName>
    <label>Old Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Person_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_Id__c</fullName>
    <label>Person Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Person_Legal_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_Legal_Id__c</fullName>
    <label>Person Legal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Phone_Kind__c.field-meta.xml
<CustomField>
    <fullName>Phone_Kind__c</fullName>
    <label>Phone Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOBILE</fullName>
            </value>
            <value>
                <fullName>LANDLINE</fullName>
            </value>
            <value>
                <fullName>SWITCHBOARD</fullName>
            </value>
            <value>
                <fullName>OFFICIAL</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Postbox__c.field-meta.xml
<CustomField>
    <fullName>Postbox__c</fullName>
    <label>Postbox</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Property_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Property_Identifier__c</fullName>
    <label>Property Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Registered_Since__c.field-meta.xml
<CustomField>
    <fullName>Registered_Since__c</fullName>
    <label>Registered Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Since__c.field-meta.xml
<CustomField>
    <fullName>Since__c</fullName>
    <label>Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Contact Sync</fullName>
                <default>true</default>
                <label>Awaiting Contact Sync</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Awaiting Manual Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Number__c</fullName>
    <label>Telephone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SE_PERSON_ADDR_CHANGED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_ADDR_CORRECTED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_DECEASED</fullName>
            </value>
            <value>
                <fullName>SE_PERSON_NAME_CHANGED</fullName>
            </value>
            <value>
                <fullName>PHONE_BOUND</fullName>
            </value>
            <value>
                <fullName>PHONE_UNBOUND</fullName>
            </value>
            <value>
                <fullName>PERSON_PROTECTION_ACTIVATED</fullName>
            </value>
            <value>
                <fullName>PERSON_PROTECTION_DEACTIVATED</fullName>
            </value>
            <value>
                <fullName>PERSON_LEGAL_ID_CHANGED</fullName>
            </value>
            <value>
                <fullName>PERSON_GENDER_CHANGED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Valid_Since__c.field-meta.xml
<CustomField>
    <fullName>Valid_Since__c</fullName>
    <label>Valid Since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ValitiveEventHandler.cls
public class ValitiveEventHandler {

    public static Map<Type, IValitiveEventHandler> eventHandlers = new Map<Type, IValitiveEventHandler>{
        ValitiveEventResponse.PhoneBoundPayload.class => new PhoneBoundEvent(),
        // ValitiveEventResponse.PhoneUnboundPayload.class => new PhoneUnboundEvent(),
        ValitiveEventResponse.PersonProtectionActivatedPayload.class => new PersonProtectionActivatedEvent(),
        ValitiveEventResponse.PersonProtectionDeactivatedPayload.class => new PersonProtectionDeactivatedEvent(),
        ValitiveEventResponse.PersonLegalIdChangedPayload.class => new PersonLegalIdChangedEvent(),
        ValitiveEventResponse.PersonGenderChangedPayload.class => new PersonGenderChangedEvent(),
        ValitiveEventResponse.PersonAddrChangedPayload.class => new PersonAddrChangedEvent(),
        ValitiveEventResponse.PersonAddrCorrectedPayload.class => new PersonAddrCorrectedEvent(),
        ValitiveEventResponse.PersonNameChangedPayload.class => new PersonNameChangedEvent(),
        ValitiveEventResponse.PersonDeceasedPayload.class => new PersonDeceasedEvent(),
        ValitiveEventResponse.PersonGuardPayload.class => new PersonGuardEvent()
    };

    public static IValitiveEventHandler getEventHandler(ValitiveEventResponse.Payload payload){
        return eventHandlers.get(payload.getClassType());
    }

    public static Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
        IValitiveEventHandler handler = getEventHandler(payload);
        if(handler != null) {
            return handler.handleEvent(baseEvent, payload);
        }
        return null;
    }


    public interface IValitiveEventHandler {
        Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload);
    }
    
    public class PhoneBoundEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PhoneBoundPayload phoneBoundPayload = (ValitiveEventResponse.PhoneBoundPayload) payload;
            baseEvent.Type__c = phoneBoundPayload.type;
            baseEvent.Person_Id__c = phoneBoundPayload.partyId;
            baseEvent.Timestamp__c = phoneBoundPayload.timestamp;
            baseEvent.Phone_Kind__c = phoneBoundPayload.kind;
            baseEvent.Telephone_Number__c = phoneBoundPayload.telNumber;
            baseEvent.Country_Code__c = phoneBoundPayload.countryCode;
            baseEvent.Area_Code__c = phoneBoundPayload.areaCode;
            baseEvent.Registered_Since__c = phoneBoundPayload.registeredSince;
            baseEvent.Provider__c = phoneBoundPayload.provider;
            return baseEvent;
        }
    }

    // public class PhoneUnboundEvent implements IValitiveEventHandler {
    //     public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
    //         ValitiveEventResponse.PhoneUnboundPayload phoneUnboundPayload = (ValitiveEventResponse.PhoneUnboundPayload) payload;
    //         baseEvent.Type__c = phoneUnboundPayload.type;
    //         baseEvent.Person_Id__c = phoneUnboundPayload.partyId;
    //         baseEvent.Timestamp__c = phoneUnboundPayload.timestamp;
    //         baseEvent.Phone_Kind__c = phoneUnboundPayload.kind;
    //         baseEvent.Telephone_Number__c = phoneUnboundPayload.telNumber;
    //         baseEvent.Country_Code__c = phoneUnboundPayload.countryCode;
    //         baseEvent.Area_Code__c = phoneUnboundPayload.areaCode;
    //         baseEvent.Registered_Since__c = phoneUnboundPayload.registeredSince;
    //         baseEvent.Provider__c = phoneUnboundPayload.provider;
    //         return baseEvent;
    //     }
    // }

    public class PersonProtectionActivatedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonProtectionActivatedPayload personProtectionActivatedPayload = (ValitiveEventResponse.PersonProtectionActivatedPayload) payload;
            baseEvent.Type__c = personProtectionActivatedPayload.type;
            baseEvent.Since__c = personProtectionActivatedPayload.since;
            baseEvent.person_Id__c = personProtectionActivatedPayload.personId;
            baseEvent.Timestamp__c = personProtectionActivatedPayload.timestamp;
            return baseEvent;
        }
    }

    public class PersonProtectionDeactivatedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonProtectionDeactivatedPayload personProtectionDeactivatedPayload = (ValitiveEventResponse.PersonProtectionDeactivatedPayload) payload;
            baseEvent.Type__c = personProtectionDeactivatedPayload.type;
            baseEvent.Since__c = personProtectionDeactivatedPayload.since;
            baseEvent.person_Id__c = personProtectionDeactivatedPayload.personId;
            baseEvent.Timestamp__c = personProtectionDeactivatedPayload.timestamp;
            return baseEvent;
        }
    }

    public class PersonLegalIdChangedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonLegalIdChangedPayload personLegalIdChangedPayload = (ValitiveEventResponse.PersonLegalIdChangedPayload) payload;
            baseEvent.Type__c = personLegalIdChangedPayload.type;
            baseEvent.Old_Legal_Id__c = personLegalIdChangedPayload.oldLegalId;
            baseEvent.Valid_Since__c = personLegalIdChangedPayload.validSince;
            baseEvent.Person_Id__c = personLegalIdChangedPayload.personId;
            baseEvent.Timestamp__c = personLegalIdChangedPayload.timestamp;
            baseEvent.Sync_Status__c = 'Awaiting Manual Review';
            return baseEvent;
        }
    }

    public class PersonGenderChangedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonGenderChangedPayload personGenderChangedPayload = (ValitiveEventResponse.PersonGenderChangedPayload) payload;
            baseEvent.Type__c = personGenderChangedPayload.type;
            baseEvent.Gender__c = personGenderChangedPayload.gender;
            baseEvent.Old_Gender__c = personGenderChangedPayload.oldGender;
            baseEvent.Timestamp__c = personGenderChangedPayload.timestamp;
            baseEvent.Person_Id__c = personGenderChangedPayload.personId;
            baseEvent.Sync_Status__c = 'Awaiting Manual Review';
            return baseEvent;
        }
    }

    public class PersonAddrChangedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonAddrChangedPayload personAddrChangedPayload = (ValitiveEventResponse.PersonAddrChangedPayload) payload;
            baseEvent.Type__c = personAddrChangedPayload.type;
            baseEvent.Person_Id__c = personAddrChangedPayload.personId;
            baseEvent.Timestamp__c = personAddrChangedPayload.timestamp;
            baseEvent.Valid_Since__c = personAddrChangedPayload.validSince;

            Type addressType = personAddrChangedPayload.address != null ? personAddrChangedPayload.address.getClassType() : null;
            Type oldAddressType = personAddrChangedPayload.oldAddress != null ? personAddrChangedPayload.oldAddress.getClassType() : null;
            
            //WE DO NOT CARE FOR NEW RAW ADDRESSES OR NULL ADDRESSES
            if(addressType == null){
                return null;
            }

            if (addressType == ValitiveAddress.SwedishAddress.class) {
                ValitiveAddress.SwedishAddress swedishAddress = (ValitiveAddress.SwedishAddress) personAddrChangedPayload.address;
                baseEvent = ValitiveEventHandler.mapSwedishAddress(baseEvent, swedishAddress);
            } else if (addressType == ValitiveAddress.RawAddress.class) {
                ValitiveAddress.RawAddress rawAddress = (ValitiveAddress.RawAddress) personAddrChangedPayload.address;
                if(rawAddress.kind != 'FOREIGN'){
                    return null;
                }
                baseEvent = ValitiveEventHandler.mapRawAddress(baseEvent, rawAddress);
            }
            if (oldAddressType == ValitiveAddress.SwedishAddress.class) {
                ValitiveAddress.SwedishAddress oldSwedishAddress = (ValitiveAddress.SwedishAddress) personAddrChangedPayload.oldAddress;
                baseEvent = ValitiveEventHandler.mapOldSwedishAddress(baseEvent, oldSwedishAddress);
            } else if (oldAddressType == ValitiveEventResponse.RawAddress.class) {
                ValitiveAddress.RawAddress oldRawAddress = (ValitiveAddress.RawAddress) personAddrChangedPayload.oldAddress;
                baseEvent = ValitiveEventHandler.mapOldRawAddress(baseEvent, oldRawAddress);
            }
            return baseEvent;

        }
    } 

    public class PersonAddrCorrectedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonAddrCorrectedPayload personAddrCorrectedPayload = (ValitiveEventResponse.PersonAddrCorrectedPayload) payload;
            baseEvent.Type__c = personAddrCorrectedPayload.type;
            baseEvent.Person_Id__c = personAddrCorrectedPayload.personId;
            baseEvent.Timestamp__c = personAddrCorrectedPayload.timestamp;
            baseEvent.Valid_Since__c = personAddrCorrectedPayload.validSince;

            Type addressType = personAddrCorrectedPayload.address != null ? personAddrCorrectedPayload.address.getClassType() : null;
            Type oldAddressType = personAddrCorrectedPayload.oldAddress != null ? personAddrCorrectedPayload.oldAddress.getClassType() : null;

            //WE DO NOT CARE FOR NEW RAW ADDRESSES OR NULL ADDRESSES
            if(addressType == null){
                return null;
            }

            if (addressType == ValitiveAddress.SwedishAddress.class) {
                ValitiveAddress.SwedishAddress swedishAddress = (ValitiveAddress.SwedishAddress) personAddrCorrectedPayload.address;
                baseEvent = ValitiveEventHandler.mapSwedishAddress(baseEvent, swedishAddress);
            } else if (addressType == ValitiveAddress.RawAddress.class) {
                ValitiveAddress.RawAddress rawAddress = (ValitiveAddress.RawAddress) personAddrCorrectedPayload.address;
                if(rawAddress.kind != 'FOREIGN'){
                    return null;
                }
                baseEvent = ValitiveEventHandler.mapRawAddress(baseEvent, rawAddress);
            }

            if (oldAddressType == ValitiveAddress.SwedishAddress.class) {
                ValitiveAddress.SwedishAddress oldSwedishAddress = (ValitiveAddress.SwedishAddress) personAddrCorrectedPayload.oldAddress;
                baseEvent = ValitiveEventHandler.mapOldSwedishAddress(baseEvent, oldSwedishAddress);
            } else if (oldAddressType == ValitiveAddress.RawAddress.class) {
                ValitiveAddress.RawAddress oldRawAddress = (ValitiveAddress.RawAddress) personAddrCorrectedPayload.oldAddress;
                baseEvent = ValitiveEventHandler.mapOldRawAddress(baseEvent, oldRawAddress);
            }
            return baseEvent;
        }
    }

    public class PersonNameChangedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonNameChangedPayload personNameChangedPayload = (ValitiveEventResponse.PersonNameChangedPayload) payload;
            baseEvent.Type__c = personNameChangedPayload.type;
            baseEvent.Person_Legal_Id__c = personNameChangedPayload.personLegalId;
            baseEvent.Person_Id__c = personNameChangedPayload.personId;
            baseEvent.Timestamp__c = personNameChangedPayload.timestamp;
            baseEvent.Given_Name__c = personNameChangedPayload.givenName;
            baseEvent.Old_Given_Name__c = personNameChangedPayload.oldGivenName;
            baseEvent.FirstName__c = personNameChangedPayload.firstName;
            baseEvent.Old_FirstName__c = personNameChangedPayload.oldFirstName;
            baseEvent.MiddleName__c = personNameChangedPayload.middleName;
            baseEvent.Old_MiddleName__c = personNameChangedPayload.oldMiddleName;
            baseEvent.LastName__c = personNameChangedPayload.lastName;
            baseEvent.Old_LastName__c = personNameChangedPayload.oldLastName;
            baseEvent.Valid_Since__c = personNameChangedPayload.validSince;
            return baseEvent;
        }
    }

    public class PersonDeceasedEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonDeceasedPayload personDeceasedPayload = (ValitiveEventResponse.PersonDeceasedPayload) payload;
            baseEvent.Type__c = personDeceasedPayload.type;
            baseEvent.Person_Id__c = personDeceasedPayload.personId;
            baseEvent.Timestamp__c = personDeceasedPayload.timestamp;
            baseEvent.Deceased_On__c = personDeceasedPayload.deceasedOn;
            baseEvent.Deceased_On_Month__c = personDeceasedPayload.deceasedOnMonth;
            baseEvent.Deceased_On_Year__c = personDeceasedPayload.deceasedOnYear;
            return baseEvent;
        }
    }

    public class PersonGuardEvent implements IValitiveEventHandler {
        public Valitive_Event__c handleEvent(Valitive_Event__c baseEvent, ValitiveEventResponse.Payload payload) {
            ValitiveEventResponse.PersonGuardPayload personGuardPayload = (ValitiveEventResponse.PersonGuardPayload) payload;
            baseEvent.Type__c = personGuardPayload.type;
            baseEvent.Person_Id__c = personGuardPayload.personId;
            baseEvent.Timestamp__c = personGuardPayload.timestamp;
            baseEvent.Guardianship_Type__c = personGuardPayload.guardianshipInfo.type;
            baseEvent.Guarded_Since__c = personGuardPayload.guardianshipInfo.guardedSince;
            return baseEvent;
        }
    }


    private static Valitive_Event__c mapSwedishAddress(Valitive_Event__c event, ValitiveAddress.SwedishAddress swedishAddress){
        event.Address_Type__c = swedishAddress.type;
        event.Address_Kind__c = swedishAddress.kind;
        event.Country__c = swedishAddress.country;
        event.City__c = swedishAddress.city;
        event.Zip__c = swedishAddress.zip; 
        event.Address_Coord__Latitude__s = swedishAddress.geolocation.latitude;
        event.Address_Coord__Longitude__s = swedishAddress.geolocation.longitude;
        event.Postbox__c = swedishAddress.postbox;
        event.Street__c = swedishAddress.street;
        event.Additional_Street_Info__c = swedishAddress.street2;
        event.Property_Identifier__c = swedishAddress.streetNumber;
        event.Number_Suffix__c = swedishAddress.numberSuffix;
        event.flat__c = swedishAddress.flat;
        event.Care_Of__c = swedishAddress.careOf;
        event.County__c = swedishAddress.county;
        event.Municipality__c = swedishAddress.municipality;
        event.Misc__c = swedishAddress.misc;
        event.Floor__c = swedishAddress.floor;
        event.Entrance__c = swedishAddress.entrance;
        return event;
    }

    private static Valitive_Event__c mapRawAddress(Valitive_Event__c event, ValitiveAddress.RawAddress rawAddress){
        event.Address_Type__c = rawAddress.type;
        event.Country__c = rawAddress.country;
        event.Address_Lines__c = String.join(rawAddress.addressLines, '\n');
        event.Address_Kind__c = rawAddress.kind;
        return event;
    }

    private static Valitive_Event__c mapOldSwedishAddress(Valitive_Event__c event, ValitiveAddress.SwedishAddress swedishAddress){
        event.Old_Address_Type__c = swedishAddress.type;
        event.Old_Address_Kind__c = swedishAddress.kind;
        event.Old_Country__c = swedishAddress.country;
        event.Old_City__c = swedishAddress.city;
        event.Old_Zip__c = swedishAddress.zip; 
        event.Old_Address_Coord__Latitude__s = swedishAddress.geolocation.latitude;
        event.Old_Address_Coord__Longitude__s = swedishAddress.geolocation.longitude;
        event.Old_Postbox__c = swedishAddress.postbox;
        event.Old_Street__c = swedishAddress.street;
        event.Old_Additional_Street_Info__c = swedishAddress.street2;
        event.Old_Property_Identifier__c = swedishAddress.streetNumber;
        event.Old_Number_Suffix__c = swedishAddress.numberSuffix;
        event.Old_flat__c = swedishAddress.flat;
        event.Old_Care_Of__c = swedishAddress.careOf;
        event.Old_County__c = swedishAddress.county;
        event.Old_Municipality__c = swedishAddress.municipality;
        event.Old_Misc__c = swedishAddress.misc;
        event.Old_Floor__c = swedishAddress.floor;
        event.Old_Entrance__c = swedishAddress.entrance;
        event.Old_Address_Kind__c = swedishAddress.kind;
        return event;
    }

    private static Valitive_Event__c mapOldRawAddress(Valitive_Event__c event, ValitiveAddress.RawAddress rawAddress){
        event.Old_Address_Type__c = rawAddress.type;
        event.Old_Country__c = rawAddress.country;
        event.Old_Address_Lines__c = String.join(rawAddress.addressLines, '\n');
        return event;
    }
    

}