force-app/main/default/objects/Valitive_Event__c/Valitive_Event__c.object-meta.xml
<CustomObject>
    <label>Valitive Event</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valitive Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Valitive_Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Valitive Events</relationshipLabel>
    <relationshipName>Valitive_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Detected_At__c.field-meta.xml
<CustomField>
    <fullName>Detected_At__c</fullName>
    <label>Detected At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Event_Subject_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Subject_Type__c</fullName>
    <label>Event Subject Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PERSON</fullName>
            </value>
            <value>
                <fullName>ORGANIZATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Organization_Legal_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Legal_Id__c</fullName>
    <label>Organization Legal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Person_Legal_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_Legal_Id__c</fullName>
    <label>Person Legal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valitive_Event__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Contact Sync</fullName>
                <default>true</default>
                <label>Awaiting Contact Sync</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Awaiting Manual Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ValitiveResponseHandler.cls
public class ValitiveResponseHandler {
    
        private static List<Valitive_Event__c> contactEventsToUpdate = new List<Valitive_Event__c>();
        private static List<Valitive_Event__c> accountEventsToUpdate = new List<Valitive_Event__c>();

    public static void handleEventsResponse(HttpResponse response){
        ValitiveEventResponse eventResponse = ValitiveEventResponse.parse(response.getBody());

        if (eventResponse == null) {
            return;
        }

        List<Valitive_Event__c> eventsToInsert = new List<Valitive_Event__c>();
        

        for(ValitiveEventResponse.Event event : eventResponse.events){

                ValitiveEventResponse.Payload eventPayload = event.payload;
                if (eventPayload == null) {
                    continue;
                }

                Valitive_Event__c baseEvent;

                String subjectType = ValitiveEventHandler.getPayloadSubjectType(eventPayload);
                
                Valitive_Event__c valitiveEvent = createBasicInfoEvent(event, subjectType); 
                valitiveEvent = ValitiveEventHandler.handleEvent(valitiveEvent, eventPayload);

                if (valitiveEvent != null) {
                    eventsToInsert.add(valitiveEvent);
                }
            }
        if(!eventsToInsert.isEmpty()){
            upsert eventsToInsert Event_Id__c;
        }
        if(!contactEventsToUpdate.isEmpty()){
            setContactId(contactEventsToUpdate);
        }
        if(!accountEventsToUpdate.isEmpty()){
            setAccountId(accountEventsToUpdate);
        }
    }

    public static void setContactId(List<Valitive_Event__c> events){
        List<Valitive_Event__c> eventsToUpdate = new List<Valitive_Event__c>();
        for(Valitive_Event__c event : events){
            String formattedLegalId = event.Person_Legal_Id__c.subString(0, 8) + '-' + event.Person_Legal_Id__c.subString(8, 12);
            event.Contact__r = new Contact(Personal_Identity_Number__c = formattedLegalId);
            eventsToUpdate.add(event);
        }
        List<Database.SaveResult> results = Database.update(eventsToUpdate, false);
    }

    public static void setAccountId(List<Valitive_Event__c> events){
        List<Valitive_Event__c> eventsToUpdate = new List<Valitive_Event__c>();
        for(Valitive_Event__c event : events){
            String formattedCompanyNumber = event.Organization_Legal_Id__c.subString(0, 6) + '-' + event.Organization_Legal_Id__c.subString(6, 10);
            event.Account__r = new Account(Company_Number__c = formattedCompanyNumber);
            eventsToUpdate.add(event);
        }
        List<Database.SaveResult> results = Database.update(eventsToUpdate, false);
    }

    public static Valitive_Event__c createBasicInfoEvent(ValitiveEventResponse.Event event, String subjectType){
        Valitive_Event__c valitiveEvent;
        switch on subjectType {
            when 'PERSON' {
                valitiveEvent = createBasicInfoPersonEvent(event);
                contactEventsToUpdate.add(valitiveEvent);
            }
            when 'ORGANIZATION' {
                valitiveEvent = createBasicInfoOrgEvent(event);
                accountEventsToUpdate.add(valitiveEvent);
            }
            when else {
                return null;
            }
        }
        return valitiveEvent;
    }

    public static Valitive_Event__c createBasicInfoPersonEvent(ValitiveEventResponse.Event event){
        Valitive_Event__c valitiveEvent = new Valitive_Event__c();
        valitiveEvent.Event_Id__c = event.id;
        valitiveEvent.Detected_At__c = event.detectedAt;
        valitiveEvent.Person_Legal_Id__c = event.subjectIds[0];
        valitiveEvent.Event_Subject_Type__c = 'PERSON';
        valitiveEvent.Sync_Status__c = 'Awaiting Contact Sync';
        return valitiveEvent;
    }

    public static Valitive_Event__c createBasicInfoOrgEvent(ValitiveEventResponse.Event event){
        Valitive_Event__c valitiveEvent = new Valitive_Event__c();
        valitiveEvent.Event_Id__c = event.id;
        valitiveEvent.Detected_At__c = event.detectedAt;
        valitiveEvent.Organization_Legal_Id__c = event.subjectIds[0];
        valitiveEvent.Event_Subject_Type__c = 'ORGANIZATION';
        valitiveEvent.Sync_Status__c = 'Awaiting Account Sync';
        return valitiveEvent;
    }

}